project_id = "yvdfdmyusdhgtzfguxbj"

[functions.setup-fernanda]
verify_jwt = false

[functions.cadastro-afiliado-publico]
verify_jwt = false

[functions.verificar-instagram]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false
